import gleam/dict
import gleam/list.{Continue, Stop}
import gleam/option
import gleam/result
import gleam/string
import utils

pub fn q9p1(inp: String) {
  let dragon_ducks =
    inp
    |> string.split("\n")
    |> list.map(fn(line) {
      let parts = string.split(line, ":")
      let number =
        utils.unsafe_list_first(parts)
        |> utils.unsafe_int_parse()
      let dna = utils.unsafe_list_last(parts) |> string.to_graphemes()
      #(number, dna)
    })
    |> dict.from_list()
  let child = get_child(dragon_ducks)
  calc_result_p1(dragon_ducks, child)
}

fn calc_result_p1(dragon_ducks: dict.Dict(Int, List(String)), child_idx: Int) {
  let parents = parent_list(child_idx)
  let child_dna = dict.get(dragon_ducks, child_idx) |> result.unwrap([])
  let parent_matches =
    list.map(parents, fn(parent_idx) {
      let parent_dna = dict.get(dragon_ducks, parent_idx) |> result.unwrap([])
      list.map2(child_dna, parent_dna, fn(c, p) {
        case c == p {
          True -> 1
          False -> 0
        }
      })
      |> list.count(fn(match) { match == 1 })
    })
  list.fold(parent_matches, 1, fn(acc, mc) { acc * mc })
}

fn parent_list(child_idx: Int) {
  case child_idx {
    1 -> [2, 3]
    2 -> [1, 3]
    3 -> [1, 2]
    _ -> panic as "child can only be 1, 2 or 3"
  }
}

fn is_valid_child(child_idx, dragon_ducks) {
  let parents = parent_list(child_idx)
  let child_dna = dict.get(dragon_ducks, child_idx) |> result.unwrap([])
  let parents_dna =
    list.map(parents, fn(p_idx) {
      dict.get(dragon_ducks, p_idx) |> result.unwrap([])
    })
  rec_check_parents_and_childs(child_dna, parents_dna)
}

fn rec_check_parents_and_childs(
  child_dna: List(String),
  parents_dna: List(List(String)),
) {
  case child_dna, parents_dna {
    // If we reach the end of the child's DNA, it's valid!
    [], _ -> True

    // Pattern match to get the head of the child and both parents at once
    [c, ..c_rest], [[p1, ..p1_rest], [p2, ..p2_rest]] -> {
      case dna_check(p1, p2, c) {
        True -> rec_check_parents_and_childs(c_rest, [p1_rest, p2_rest])
        False -> False
      }
    }

    // Safety catch-all (e.g. if DNA lengths don't match)
    _, _ -> False
  }
}

fn dna_check(
  p1_dna_seq: String,
  p2_dna_seq: String,
  child_dna_seq: String,
) -> Bool {
  let parents_are_equal = p1_dna_seq == p2_dna_seq
  case parents_are_equal {
    True -> p1_dna_seq == child_dna_seq
    False -> p1_dna_seq == child_dna_seq || p2_dna_seq == child_dna_seq
  }
}

fn get_child(dragon_ducks: dict.Dict(Int, List(String))) -> Int {
  list.range(1, 3)
  |> list.fold_until(0, fn(acc, child_idx) {
    case is_valid_child(child_idx, dragon_ducks) {
      True -> Stop(child_idx)
      False -> Continue(acc)
    }
  })
}

fn calc_result_p2(
  dragon_ducks: dict.Dict(Int, List(String)),
  parent_idxs: List(Int),
  child_idx: Int,
) {
  let child_dna = dict.get(dragon_ducks, child_idx) |> result.unwrap([])
  let parent_matches =
    list.map(parent_idxs, fn(parent_idx) {
      let parent_dna = dict.get(dragon_ducks, parent_idx) |> result.unwrap([])
      list.map2(child_dna, parent_dna, fn(c, p) {
        case c == p {
          True -> 1
          False -> 0
        }
      })
      |> list.count(fn(match) { match == 1 })
    })
  list.fold(parent_matches, 1, fn(acc, mc) { acc * mc })
}

pub fn q9p2(inp: String) {
  let dragon_ducks =
    inp
    |> string.split("\n")
    |> list.map(fn(line) {
      let parts = string.split(line, ":")
      let number =
        utils.unsafe_list_first(parts)
        |> utils.unsafe_int_parse()
      let dna = utils.unsafe_list_last(parts) |> string.to_graphemes()
      #(number, dna)
    })
    |> dict.from_list()
  let duck_idx_list = list.range(1, dict.size(dragon_ducks))
  get_parents(duck_idx_list, dragon_ducks)
  |> list.flatten()
  |> list.map(fn(combo) {
    let #(child, parents) = combo
    calc_result_p2(dragon_ducks, parents, child)
  })
  |> list.fold(0, fn(acc, el) { acc + el })
}

fn get_parents(
  duck_idx_list: List(Int),
  dragon_ducks: dict.Dict(Int, List(String)),
) {
  list.fold(duck_idx_list, [], fn(acc, child_idx) {
    let possible_parents = list.filter(duck_idx_list, fn(i) { i != child_idx })
    let parent_combos = list.combination_pairs(possible_parents)
    let combos =
      list.fold(parent_combos, [], fn(acc, parents) {
        let #(p1, p2) = parents
        case is_valid_child_parents_combo(child_idx, [p1, p2], dragon_ducks) {
          True -> [#(child_idx, [p1, p2]), ..acc]
          False -> acc
        }
      })
    [combos, ..acc]
  })
}

fn is_valid_child_parents_combo(
  child_idx: Int,
  parents: List(Int),
  dragon_ducks: dict.Dict(Int, List(String)),
) -> Bool {
  let child_dna = dict.get(dragon_ducks, child_idx) |> result.unwrap([])
  let parents_dna =
    list.map(parents, fn(parent) {
      dict.get(dragon_ducks, parent) |> result.unwrap([])
    })
  rec_check_parents_and_childs(child_dna, parents_dna)
}

pub fn q9p3(inp: String) {
  let dragon_ducks =
    inp
    |> string.split("\n")
    |> list.map(fn(line) {
      let parts = string.split(line, ":")
      let number =
        utils.unsafe_list_first(parts)
        |> utils.unsafe_int_parse()
      let dna = utils.unsafe_list_last(parts) |> string.to_graphemes()
      #(number, dna)
    })
    |> dict.from_list()
  let duck_idx_list = list.range(1, dict.size(dragon_ducks))
  get_parents(duck_idx_list, dragon_ducks)
  |> list.flatten()
  |> echo
  0
}

pub const sample_input_1 = "1:CAAGCGCTAAGTTCGCTGGATGTGTGCCCGCG
2:CTTGAATTGGGCCGTTTACCTGGTTTAACCAT
3:CTAGCGCTGAGCTGGCTGCCTGGTTGACCGCG"

pub const sample_input_2 = "1:GCAGGCGAGTATGATACCCGGCTAGCCACCCC
2:TCTCGCGAGGATATTACTGGGCCAGACCCCCC
3:GGTGGAACATTCGAAAGTTGCATAGGGTGGTG
4:GCTCGCGAGTATATTACCGAACCAGCCCCTCA
5:GCAGCTTAGTATGACCGCCAAATCGCGACTCA
6:AGTGGAACCTTGGATAGTCTCATATAGCGGCA
7:GGCGTAATAATCGGATGCTGCAGAGGCTGCTG"

pub const q9_input_1 = "1:TTAGCGCTTCGGGAGATTTAGCACAAAAAATCTTCCCATCAGCCCAATAAGTGTGGCGGTAGGACGAATCTAAGATAGCTCATTCCACGTTTTGGGTAAGACAATTGCTCTTCGCTGGGGCATAGTCT
2:ACACTGGACAGATATGCTGGCAGCTGTGCTGTAAGTGGGGGCCCTATCCTACTCTCCAAACAGGATGCGGATTGCCACCTGTCCTTCCTTAGCTGGAACACAGTAGAGCGTTAAGATTACGCGGTAAA
3:TTAGCGGATAGGGATATTGACCGCAATACTTCATGTGATGAGCCTAACCAGTGTTCCAGAAGGACTACTGAAAGACACCTGTCTCTCCTTTTCTGGAAAACAGAAGGGCCTTAGGATGACCCTAGAAT"

pub const q9_input_2 = "1:GTTTAGAGTGGGATTTGCTTGAGTGGCACGAGGCCTAAGCAATCGACTTACGGGAATTCGCTACCTCACAATCGCACCCTAGGTCATGCGTCTGAGGTACTGTAGTAAGTCCAATTGAGGGCTCCAAC
2:GTATTCGGGGATCTCTAGGTTAGCGATAGCAAACTACGGGACTGTCTAGGCCGTCTGGCTTACGACCATCGAGACAACGGAGTAACCAAGGCAGATTCTTTCATTCGTCGAAGTGCTATTCGAACAGT
3:TTGTCTGTCTATGAGTGGTGGCCTCCGCACGATATCCGTGGATTCGCTCTGTCATATCTATCCCCTTGTTATTTCGAACGCTCGCCCTACTGCTACCACCGGAAATACGACATTTATGAGGAAACACG
4:AACCGCTTAAGTTCCCAGGTCCCACTCTTCAGCTGCGACTGAAAGCTGATTATACATTGATCATGACACATAGGAAAGAATCTGCTCCTCTGGTCTTCACTAGAGGTACGAGCCTTGGTAAGGGCAGA
5:TGGTCTTTCCACGCCTGGTGGCCGCCGGACGATTGCCGTCGATTGTATCTAACAAATCTGTTCCCTAATCATTTCGGACGGTCGCCCTACGCCACGGACTGCAACTTCAACAGATACGAACATCGGCG
6:AGTTAGGTTCCATATGAAAGAGACAGGCTAAAAAACCACAACATGTCTAAATAAAGGCATCGTAGGCGTAAAGCAACAAACAGGTCACAAGTCACTAAGCACAGCGCCCTGGTAGATGGAGCAGATGT
7:AGTTTCCCCCGCTACGGATCGTCATATTGATAAGAGAACGACACGGAGTGATTGTCCTCAAAAGCATGCCTCAGTCCCGGGTCCCGAAACATGGGAGGATGCGAGCCACTTCACTATTCTCATCTTCC
8:AGTTTACCTCGCTACCGCTCATCATGCTGCTAAGCCTAGGGCCCATCGTCCACGTCATTGAAAGCTTGCCCCGGTTCCAGGCCCCCAAAGATGGGAGCGTGAGAACCTCTTTACTATACTTACCTTTC
9:ATTTAGAGTCCAATAGCACGAGACTAGTTAAAATCCCACGACATGACAATTATCAGTCATCGCAAGCGCATATCATCAAGCCGCTCGAATATCAGCAAACACACCGCCGTGTTGTAGGGTGCCGTCGA
10:GGGGGATTACTGTCGTCTTGTTCATCGAATATCGAAGATGTTCACATTTCGTGCGTTGCTCGTGGGATGCCAGGCCCATGTGCGAGGACCGAACCTATAAGACCTTATATAGAGTGCTGAACAAGCAT
11:CCATGGGAGTTTGGGCAACGTCTTGCAATGCCCGTCAGGCTCGCATAACACATAGGCAAAAAAGTAGCTCGTATCCGCCTCAGCCCTATGCAATTCTGGTAAGTGCGCATAATTAAATATTATAATCC
12:TTATTCGGTGATGTCAATGTTTAGAGGCGAAAAAGAAGCGACTTGGTAGACCGTTTTGCTTACTTCCACCGAATCAAGGGGTCAACCAAAGCAGTAACCATCAGCAATGTATGCGAATTCCGAACTGG
13:AGCCTATAGCAAGCCAGAGACATCAGAGCCTCCGCGGCCTCGGGAATAATTGACGACAAGTAAGCCATAAACATAGTCGTTAACGCCACATGCTATGCACTGTTACCGGCGGTCTACTCAGTCCGCGA
14:TTTTCAATGGGCCTCTGGTCAAGGGACACGCCACAGGCGAATAAGCGAATAGTCACGGAACTGGTTACCCAGCCCCCAAGTCTAACGTAAGCAACGGTAGGCCGGTACTTGAGCGACGACAGGTCGTT
15:TCGCCGACTCGTAGGTGACAGAGAATAAGTTGGTACCAAATGGAGTATGGTTAAAAGGAGCTCGTTCCCTTTGTGAACGTAAGGATGTACACATAAGATTCATCATAGCACGCCGGACGTCGGGGGAG
16:TCAGCACTTACTTGAGGTTGAAAGAGCTGACGACCCCAGGTCCCGTTGACGCCTTTTTCGTCCCCTCAATATACAAACTGACACGGCCTAGAGGCTTGCGCTCCACCCCAAAAAGAAAGGAATAGTCG
17:AACAATCTCAGTTACAAAGTAGTAATCGTCGCCTGGGGCCGGGGTCTTAGAATATAATGTCCATTACACATAGCAAAGCAACAGCTCGGCTGGGCTTCAAGATAGGCACTATCCTTCTTAAGGGCAGA
18:TCCGTTGACGCGGATGTACTCCGGTTTGTACTGCCTTGCAATACTTGGCTTTACTGAGAGGGGGCCGCTTGACTAGTAGGGTTGCGAGAGCGCTATGAACTCCTTGCATACTTAACCCCGTCCAACTC
19:CCGAATCTTCCTTCGCTCAGCGCGCGTGCCTGTCCCAGTGCCCGCACGTGTCGCCGCTGAGCCAATGCCACGTGGATCCCGGCAGACTTCTGGGCGTTTTACACGATAGATAATTCTCTTCACAGTAT
20:ACACGGGAAAATGGGCTACTTCTGGCTATGCCCATCCGCATCGCAGGAATTACAGAAAAAAAAGCAGGACGTTCCGGCCGTTTCGCTATGCAACAACGGTAAGTGCACAAAATGTAACGTTTGTATGC
21:CCACGCGTGTTATGTAAAATGCTGGCAAAGCCGATCAGCATGGCAGGAAACACAGGAAAAAAAGCAGCAGGCTCCCGCCTTTTCGCTGTTCAATACTTATAGGTGCACAAAATGAAACATTATAATCC
22:ACGCGATGGTCGCTATATCTTTGAAACGTTATAGCTCGAGGAATTTAAACCCTATCCCGTGGTAACCGGATGCGTTAGCAACCTTTACGAGTGGCCACACGCTGATTCATTAGATGATCGACCAAGGG
23:ACGGAAGAGACGCCCTAGCTGGCGGAAGTACGGACAGGATATCGTTTCCTTGGCTGAGAGGCGCCAGCATGAACAGTAGTGTCGCGTTATCGCTGCCAAATGCTTGCATACTTTAACAAGTCCCACTC
24:GGGGGGCTAATGTGGGCTTTGTCGTCTCATACAGAAGGCGTCCATATTCTGGACGGTACTCGTGGGGTGCTAGTCGCATGTTCAAGGATCTACGCTTTAATACCTTTTGTTGAGTGCTAGACAGGGAT
25:GCTCCATTTGAATGCTGGTCGTCGTTCAGACCAGAATTGAATAAGCGAAAGGCTTACGACCTCTTTAGTCACACACCAACACTACTGTAACCAATAGTACCGTGGTCTTTACGCGACACTAGGTCCTA
26:TCGACTACCCCTTTGTTTACCTGTGCCACTACCAGTTGAGTAGTTTTGGTTTCGTCAACGGGTAATTTTTGTGGGACCTAGAGAGGCATATTGAGAATTAAATGTCGGATCGCAACAACGTTTGAGGA
27:CGAATACCTCGCTTGGCAACTTGAGTAAGTATCCGACTGTAATCTCGATAATGAGGTGAGTCCACTAAGAGAACCATATTGCTAAGCATCTGAGCAGTACGGGCAGTGGAGAGACCGCTACACTTTGA
28:TAGCTTCACTCTATCTTATAGCCTGCTTTCGACCATTCGTAGTGACCGGTTTCAAACGCGTTCTCGATGCTCGTGCGAGTGGGTTCAGATAGCTAGATGCCTTAATGTAACGTATCCAGGAGTGGGGA
29:GGATGACAGCAGCTATAGACGAGCGATAGCACACTACGGCGATGTCTGAGCTTTCTGGCGATGGAATTTTGGGATTGCGGAGTGACCAAGGGAGATTTTTTCATTCGTCGGAGTCCTAGTGAAAGACT
30:GTCGGGCTCCGCGTTCAATGCTCGTGGGACTGGGAGGTGAACCTGCCTTCTGGCTTGGGATTGACATAATCTATCAGCCGTCTAACTCGCAAAGACAGGCTATTGAGCTATCTGTCAGTGAAGCCGAT
31:GTGATGAGATTTGTCATTGCGTTTGGGGCGGAGATCATGGAGTAACGGCTCAAGACGGGCCAAGTCACCAATACTCACATTGTAGTTAGGCGTTCGCCAACTCCAACTGGAACGTAACAGGACTCAAT
32:GTGTATTCATGGTTCATCGTGTTTGGAGGGGCCAGTATGCCGTCCCTAGTCAAGCCGCGCCAAGTTATCCATGCTCAGATTGTAACTAGCCCTTCATCGTCTACAACTGCAAGTGACCCGGACTCGAG
33:CTGTTGTATGTGACGAAGGCGATGATGATCAATAGGAGCCTACGGACAATTTATGCCCCTACGCATCAGACAACTAAAGAGCGCCCTCTAGTTGCCCGGAGGAAATTATACCAACGTCCTAGTTTAGT
34:ACAACCTATATCCGGGATGAGTAGACGTTCAGCTTGTATCGGTGTCAAAGAAGCCAGGCGCCGGGCTGTACGTCGTGCACATATTTTACCAGTGTATGTGGATTAGTTTCTACGGACGCAGGCCACTT
35:ACCGTTAAGACGCCTGTGCTGCCATTAGTACTGCCAGGATATACTTGCCTTGACTGAGAGTGGGTCGCTTTACCACAAAGATCTCGATCTCGCTACCAGCTGGTTGAATGCTAAACGAAGTGACCGTG
36:CTCTTGTCTGTGATGTCGGCGAAGACGATACGTAGGTGACTAGGCACAACTTAGTCCCCCCCGTAGTGCACACGTTCACAGCGCCATCTAGTCGACCGCAGGCAATCGCTCCTACGTGCGAGTTTAGT
37:ACAAGCGAGAACCGCGATTTGCAGTCATTCTGCCTTCATTGGTGCTCATGAAGTCACTCACCTGGCAGTACGTTGCGCGCACATGATACGAGTGAATCTGGCTTACTTTACGCCATCGCAAATCGCTT
38:TTCTGTTTACTTGCCTAGTGACCTCGAGACCATTGCTTTCCATTGGCTCAGTGAAGTCCGTTTCCTTGGCTTTCCCGTCGCTCGCCATTCTCTAAGCGCTGCGAAGACGATAGTTACGAGCAACGGCG
39:AGTTGAGCTATCTTCGGATCGACATGTTGCAAGAAGTACGGCCCGTCGTCCTCGACCTTAAGACTTTCCCTCGATTCCAGGCCCTCGAACAAGTGAGGACGCGAGCAAATTTAGTATACTTATCATCC
40:TAGTCTGATTTACATAAGACAGACATGTGTGTGCCGCGCAGCCCGTTGGGTTAACCATCGTATGTGCAACTCGCAGGAGTAATCGGCAGGAGGCATAGTCCGCCGTGAAGACCGCTTCGGAGTCCCCC
41:GTCCCAATGCGCCTCTGGTTGTGGTTCACACCCCAGTTTAATCACCGAAAATCCAACGAACTCGAGCCCCAGACAACAAGTCTAATGTAAGCACTGGTTGCGCCCTCCTTGCTCGAAGCTTGGTCCCT
42:ATGCAGGCGGTTTATCATTTGTCTGCCACTAGGACTAATGAATCGACCTTTCGTATTACAGGACTTCATACCAGCACGCTGTGTAATACGTCTCAGCTGTTGTGCTACTCGCAAGTGAATAATTACCC
43:GCGCGGGTCTGTTTTAGGCCATAGTACGAGCGGGGGGGTAACCGGCGTTCTGGCATTGGTTCAAAATTGTCGTTCACTTGTCTGACGCACACCAACAGCGTAGGTACCTATTCGTGGGTGATGTTGAT
44:CTTCTGGGATGACTAGGCTTAATGAAACCATTATTGGACGCACGGGAAACGACATCTGTGCGGCGAATATGTAAACTGTCTTGACAACCGTCGAGTCCTGAGCAAAACGTTTCGTAATTAGAGCAGGC
45:TCGAGCTGTCTGCGGTCATTTGGATATGATAAAGCCCAAGGCATGATAACCCTAGCATGTGGCCACCTGATGCGATCGAAACACAGCAGAGTTGTCCGTAGTCCACACATCACAGAATCGGCCTAATG
46:TTGTCTCCCTTACAGATGACAGCGATCAGTGTTCCGCGCACCGCACGTGGTCCAGTGACATATGACCAAGTGGTTTTCATCGTCAGAATGAGGCATATGAAACCGTCAAGACCGTTTCAGACACCCCC
47:GGGGGGCGAATTTGGTTTTTGTCAGCTCAAACCGTAGGTAATCATAGTCTGTACGTTACTCGGGTGAGGCTAGTGCGATGATGGAGGATCGACCGTTAAAGACTCTTTGTTGAGTGCAAAATAGGGCT
48:CAACCTTGTCTCTAGGACGAGTATATGTTTAACTTGTTACGAATTCACAGGGGCTAGGAGCCGCGCTGAAAGACGTTGAAATGTTTCAGCGTCCTGAGTTCAGTTGAATCTACGGATGCCGGCGATAG
49:TTAACGACATCTTTTTTCACCCATGACCCGCCCGGTGGATTTGCCATGGGCTGATCACCCGGTAAGTTTTGAGAGACGTATAGACGTACATAGAGAACCGGATCCCGGATAGCACCAGCGTTTTACCG
50:GAAGTACCAATATGCGATGGCAAAACCTGACGTCCCCGTGTCGCACTGCCACATTTTACGACCCCCCATTAAACAAACTGACACGGCAGACAGGGATACACCCCACTACACTGCGTACCAACTAGTCG
51:GAACACCAAGGTTCCAAAGTCGCAATTTCCAGTTGGGGCCGAGATCAGGGTACACATTGTTCATTAGCCACACGGAAGAATCAGCTTCTCCGGTCTTCACGTGCGCCACTATCGTTCGTCCGGCCTGC
52:GCTTAGAAGCGTGATCGTATAATTTCTCTTTTGTTAGATTCTTGACACGTGACATTAGGTATAAACAGTAACTGCGAGAAGAAATGAACTGACCAATATTTTATGAGTTGCTCGGGATCCATTGAGGA
53:AACTTCTAACTTTCGACGGCGGTGACCATAAATCAGACACGAGGGAATGCTAATTCCCCCCGTCAGCAGACACGTACCCCAATCCCTGAATTTGAGCTCAGAATGTTGTTCAATTGACCTAGTCTCGT
54:TGTTATTCAGGGTATAACATATTTGTAAGCTCCTGTAAGCCTGCCATAGACACACCGCTGCACGGTGTCCACGCATTGGTTGCTACGTGCACTGTATGGTTGAGTTCTCCGGGTGTCCCGGACGAGTG
55:GCGGCGAGTAGTACGTGCGGTATTACAAGTCTGTATTAAACGTAATAAGATTAAAAGAAGCTGGAGTCCCTGCTCCTCCTGAAGATGTCCACATTTATATTCGCACTTAACATGCGAGGTCGGGCAAG
56:GATTGTAGTCGGATATGCCTAAGTGGAACGCCGCCAAAGCAGTATCCTTACGTGCAGTCGCTTACAGACAATCGGACCAAAGGACCTGCGTCTGTGGTACCATAGTAAGTCAAGTACAGGGCGCCAAC
57:CTGCTGGGATGACAAGCTCTAATCATACCATTTCTGGACGGTTCATAAACTTAAAGTTCATGGCGGGCTGACAACGAGTCTTGAAAACCTGCGAGTACTGAGCAACACGTGTTGTAGATAAAGCAGAC
58:AGAATTCAAAGCTACGGAACTTGAAAAAGCATTCGAATGTAGAATCGCGATGCCGATGAGTACATTGACATTACGAGATTGCAATGCACTTGAGCGTTACGGGCACTGGTGCTGCCGCAACAATCCCA
59:GAGGTGCCAGTAGGCTAAGTCACATCTGGGTGTCAACGTGTCGCACCGCCATATCTAATCACATCCTTTATAGATAACGGCCACCGAAGACTGGGACACAACCTATTACTCTGCGTACCAGCCAGGTG
60:TCGCGCCGTTTGCTATCATTATGCAACGTTAAGGACTAACGAATTATCACCGTATCCCGTGGTCTCGGGTTGCGTTATCACCCTTTCAGAGAGGCTAGACGTTGCTACATCACAGAATCGGCCTAATG
61:TCCCCAACCCCTGGACCACAGCGACTCCGTTGTTTCCGGCTGGAGTGTGGCTCCAGAGTGGTCCTTCTGTTTGTGAAGGCACGAGTGTAAGCTCAAGATTCATGATAGCTTGCCGAACGAGGTTGGCG
62:GAGTGTGGGCTTAAATGTTTATGTGGAACGACGCCTAAGCAGTAGCCCTACGTGCTTTCAGTACTAGACAACCGCACCAAAGGAACTGCGTCTGAGGTACTATAGTACGTCAAGTACAATGAGCACCC
63:TAGGTGCCAATTTGAGGTTGAACGAGTTGATGACAACAGGTCGCACCGCCGTATCTAATGACCTCTTAAAATGATAACGGACACGGCATAGTGGCATGCGATCTACCCCTCTAAGTACCGGCTAGTTG
64:CATCTTGGCTGAATAGCCTTAAGCATAACATTATTGGACGCTTGGGAAACTTCTAGCTTGTGGCTAGTAGATTAACAGTCCCGGATACCGGCGAGTCGTAGCCAAAAGATTATTCAGTTAATGAAAAC
65:CCCCCATATCACATAAAAGGAATAGGGTCCTCCGCGGCCACGTGGAGCATTGTGAACATGTTAATCGCGCACATACGTGCTTAGGCCACCGGCTATCGAGTGTTACCTACGATACTAACAATCAGCCA
66:TGTTTTTCAGGTGACAACGCGTTTGGAGCGGCCTGTATGGAGTCCATAGACACGCCGGGCCACGGCGTCCATACTTAGGTTGTTACGAGCCCTGCATCAACTACAACTCCGACGGACCCGGACGCATG
67:TCTTCCTTTGAATGTTGGCCAACAGAGCGGCCAGAAGCGGAAAAGGGATTGGTTTCGGACCTGTTTAGTCACCTCCCAACACAACCTGACCCAACACGACGCTGGGATTTAAGCGACAACATGGGGTA
68:AGCCCCTATCCAATCAGAGGCATAATAGGGTCTGCGCGATCGGGATGCATTGAGAACGAATAAATCGTACTCATACTCGCTAAGACCACCGACTATGCAGTGTAACCGGCGATCTACACAAGCCGACA
69:ACTTGGATGCATCATCATCTCGATGTGTTTCTGCCGGAAACTTTACGTGGTACATTAGCTTTAACCAGGCGCTAGCAAATGACAGGAACTAAGTATTACTGCGTGACCCACTCGAAATGCGATGCAGT
70:GAAAATCACGGCTACACAGTAGTAATTGCCGCTAGGAGACGGGGTGATGGAACCTAATATCCCTTCGCCGCACCGTGCCAACAGCTTGGACCTGCTCCAAGTTCTCCACTTTTGTTCTTCCGCCGTTC
71:TCTACATCTACCTGTGTACTAACATTCCTTAAGGGCCTTCAACGAATCACGATGGTCTAACAAGATATTAATATAGTGCCCGCGATTCGAAAGGCTGTGTGGTAGTGAACATAATAGGCGAGCATGAG
72:GCGCGGGTTTGTTGCAGGCCACAACACTCGCGACGGAGTAAGCGGCGGGCGGGCATTCATACATATTTGAAGTACTCTTGGGAGTGGCACGCCAGCAGCGTAGGTGCCGATTCCAGGCTAATGTTGTC
73:CAACTCGATCAACGTCACACCCACATGTCCAGGAGGGACAGGCGGTTGTGTTAGCCATCGTCTGTGTACCTCGCAGGAGTAATGGGCGGGGAGTGTGGTCCGACGTGCAGTCTGCGCCGTAGTTAAGA
74:ACATGGATGCATGATCACATAGATGTTTTTCTTTCAGGTTTTTGTTGCGTTAACTAAGGTTTACCGTATCACTGGGAAATATCATAACCTGACCGATACTTCGCTTGTTGTGCGGAATGCGACGCGTT
75:ACATGGATGCAACATCACCACGACGTGTTTCTTCCGTGAATTTTTTGTGGTAACTAAGCTTTACCGTAGCGCGAGCAATTATCAGACCAGAAGTGTTACTGCGCTTCCCATGCCAAAAGAGACGCATT
76:TGATGCCGGGATCTATAGGTTTACAAGAGCACACTAAGGGGATTTGTAAACCTTTTTGCTTTGGACCTTTGGGTTTGCGGGGCAACCAAAGGAGAAATCATCATTAATCTATGCCCTTGCGAAAGTCG
77:CAACCTGATTAACATATGACACCCATCTCTGGTAGGCGCAGGGGATGTGGTTCGCTGTCGTATGACCAAGTGGTTGGCGTCGTGGGAGGGGGGCATAGGACGCCGTCAAGACTGTTTCATACTTCAGA
78:GAGCGTACCTTAAAAGCTCACAGCATAAGATTTCTGCCCTGTTCATACACTTATAGCTCATGGTTGGCTGACTTCGAACCCCTGATACTTGCGATGAGTAGCACACCGAAGATTCAGACGATGAGAAT
79:AGTTGCGTCATCATGGAATAGAAATATTTAAGGAAGAACGACACGGACGGATTGACCACAAGGCTATCACTGAATCCCGTCTCCTGGAACGAGTGTGGACCCAAGCAAAATCGGCCGTCTCCTTATCC
80:AACATCGCACTTTTATCGGCGGAGTCCACACGCCAGTCATGTGGCAATGCTAAGTGCCCCCGTTAGTGCAGACGTTCCCCAATACATGAATTCTAGTTCGCACTGACGCTCATTTAAGTGTATCTCAT
81:AGAGTTCAACGCTAGGGTACTGAAATAGGCGCCGTTCTGGAGACCCGATGAGGCGATTAGTCTATTGCCGGTACCCGGTGACTATCCATCTGTCTGTTAGGCCATGTGATCAGACCGCAACAATCTCA
82:CGACGGCGAATTTGCGTTTTGCCGGATCAAACAGTAAGCAACCATAGTCTGGACGGTAGTCTGGTAGGCCTAATGGGAGTATGAACGATGTCCGGTTAAATATTCCTAGTTCTGTTCAAGCTAGGGCT
83:TGGACTGTCTACAAGTGAACGGAGCCGCCAGCGATCCGGGGATTCTATCTAACATATTTATCCTCTAATTATGTCGAAGGGTCTCCCTAAGGCTCCGAACGGAGCTTAAACCTAAATTAAGTTACACG
84:TAGATTTACTCTTGTGTACTGCCAGCTTTCAAGGATTTGTAGTGACCGGTTTCGGTCGAATAAGCGATGAACATGCTGCTCGGTACACAAAACTCTATGTCTTAATGTAACGTATACAGGAGTATGAG
85:TCGAACCTACTGTTGCCCAGTCCGCCTGACTGTCTCAGTTGCCTAAGGCGTCCGCGCTGAGACTATGCAACATGCATGCCCGCGAGATCCTGGGCGTCATCGACGATTCCTAATGGATTTCCGAGTAT
86:GCCGCAACCAGTACACGACAGCGTATCAGTCGTTTCTGGATGGAATGAGGTTAAAGAAAGGTGCTTTCCCTTGTCATCGTACAAGTGTCAACTCTTAAATTCGGACAGAATATGGAAGGAGGGTGGAG
87:ATAGAGGTTCAATTACCGAGAGTCAAGCTAAAATCCCACGACCCGTGACTATTATGTCATCACAGGCCTATATGAACATGCAACTCAAGTATCACCAAGCACAGTACACAGGTGGAGGGAGCAGATGT
88:CGAGCACCTCGCTTGGCTTCTGATGTAGGTGCCGTTCAGGAATCCCGATGATGAGGATATGCTTCTACGGGAACCCTGGGACTAACCGTCCGTCTAGGAGTCCATGAGAACAGACCCTTATTCTTTGT
89:TGGATCCCTCTTCGGCCATTAGTCTATGATAAGGACTAACGCCTGATCACCGTAGGATTTAGCCTCGTGTGGGGATCTACCCACAGCAAAAATATTCGTATTCCCCAGGTCACAGAAGCTGCCTTATA
90:TAGCCTCATTCTTTTGTATTGCCTTTTTTTAAGCGCTTTCAATGACTGATTACAATCGCGTACTCGATGAATATGCTACCGGCTTCTGAAAGCTATATGTGGTAGTGAACAGAATACGGGAGTAGGAA
91:CCAGGTACACCTTTTTGCATTCGCGACACGAGTAGTGGATAAACCTGGGGTACGACAACCGGAGATTTTTGAGGCACGTATAGAGGCACAGTGTGAGCCGAACCCCGGTTCACAACAATTTGTGACGA
92:GGAGGGGTATAATATCAGAAATTAAGCCTCCAGAACAGCAACCCGTGTCAATAATGGAACCATAGGACTAAAGGGATATATAAGCCACGAGTTCCTAAGGCGAGTACACATGCAGTTGAATCAGATGT
93:TCGGAAGGCGCGGACTAATTCGGGGATGTACGAACTTGCACTCGCGTGCATTGCTAAGAGGCACCAGCATGGATAGTCGTGCTGCCTGAGCGCTGTGCAACCCTTGCTGAATTTCACCCGTCCAACTC
94:CAACCTGGTCTCCGCGATTTGTAGTCATTCTGCCTGTTTCGGAGCTCCAGGGGTCAGGAGCCGCGCAGAACGTTGTTGACACGTTTTAGGGGTCTAACTTCATTACATTCCGCGATTGCAGGCGACTT
95:CGAAGTTATACTACTCTCGCCGCGAGGGCTAGGCCTACAGCCAGCTCTTAGGGCTCATACTCCACTACCACGAGGTACCCGACAGACATCGGGAAGTTTTACCCAATAGAAACTTCTCTTTACTAGAT
96:TTGACGTCCTTTTAGTTTACCTATACCCCTCCCGGTTGAGTTGTTATGTTCTGATCACGGGATAAGTTATTTGAGTTCCAGGGACATATATAGAGAATTAGATGTCGGACAGATCATGCGTTTTAGCG
97:TGGAACCTTCCTACGCTCGGCCCGACTGCTAGGCTCACATGCCTATGGTGGGGCCGATACTACTCTGCAACATGGATGCCGGCGGAAATCTGGGAGTCTTCCCCAATACCTACTGGATTTTCCTAGAT
98:CCCCCCTGTCCCATACAACGAATAGTGTGGACTTTTCGAAGGTAGTGCCACGTGAACGTAATAATCGCGCTAATTCGTGCTTAGACCACCGACCTTCGGGGATAGACTACAATACTAACAAGTAGACT
99:ACACTCGTAAAATTTATCATGTTGTCTAACGCGATCCTCAGGGCAGGGATTCCAGAAAAAGAAGCGAGAGACTCAGGCCGTTTCGCTGTTCGACAACTAGAGGTTGACCAAAGGTAACGGCTGTCTGT
100:GTGCGGGTCTGTGGCCGACGCTAACAGTCGTGGGAGATTAACCTGCGGTCTGGCATTGGTATATCTTTAACTAACTCTCGGCAAACTCACAAAAGCAGGCTAGGGGCCGATCTCAGACTGAAGCCGTC"
